2021-03-23 14:51:58,802 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-23 14:51:58,803 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-23 14:51:58,808 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T06:54:58.8063272Z","ttl":180,"modifiedIndex":140,"createdIndex":140}}

2021-03-23 14:52:02,811 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-23 14:52:02,813 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 60599012fe754e374820d6b3 mem_id=1997672709712
2021-03-23 14:52:02,814 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  60599012fe754e374820d6b3 
2021-03-23 14:52:02,815 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-23 14:52:02,816 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-23 14:52:03,803 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-23 14:52:03,806 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-23 14:52:03,807 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-23 14:52:03,808 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-23 14:52:03,809 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 141
2021-03-23 14:53:06,803 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 141 -> 141
2021-03-23 14:54:11,805 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 141 -> 141
2021-03-23 14:55:18,809 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 141 -> 144
2021-03-23 14:56:23,800 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 144 -> 144
2021-03-23 14:57:29,808 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 144 -> 147
2021-03-23 14:58:30,812 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 147 -> 150
2021-03-23 14:59:36,805 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 150 -> 150
2021-03-23 15:00:40,807 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 150 -> 153
2021-03-23 15:01:47,810 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 153 -> 153
2021-03-23 15:02:53,802 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 153 -> 156
2021-03-23 15:03:55,806 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 156 -> 159
2021-03-23 15:05:05,813 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 159 -> 159
2021-03-23 15:06:08,821 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 159 -> 162
2021-03-23 15:07:11,824 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 162 -> 165
2021-03-23 15:08:12,564 - ServerEntity.Puppet - INFO : [ServerEntity.py:21]: __init__ create entity Puppet with id 605993dcfe754e374820d6b4 mem_id=1997674245424
2021-03-23 15:08:12,565 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  605993dcfe754e374820d6b4 
2021-03-23 15:08:14,817 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 165 -> 165
2021-03-23 16:25:19,627 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-23 16:25:19,628 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-23 16:25:19,642 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T08:28:19.6409705Z","ttl":180,"modifiedIndex":213,"createdIndex":213}}

2021-03-23 16:25:23,631 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-23 16:25:23,632 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 6059a5f3fe754e3c3c10e1af mem_id=2278977531616
2021-03-23 16:25:23,634 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059a5f3fe754e3c3c10e1af 
2021-03-23 16:25:23,635 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-23 16:25:23,636 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-23 16:25:24,637 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-23 16:25:24,640 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-23 16:25:24,641 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-23 16:25:24,642 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-23 16:25:24,643 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 214
2021-03-23 16:26:10,600 - ServerEntity.Puppet - INFO : [ServerEntity.py:21]: __init__ create entity Puppet with id 6059a622fe754e3c3c10e1b0 mem_id=2278978332896
2021-03-23 16:26:10,602 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059a622fe754e3c3c10e1b0 
2021-03-23 16:26:14,226 - ServerEntity.Puppet - INFO : [ServerEntity.py:21]: __init__ create entity Puppet with id 6059a626fe754e3c3c10e1b1 mem_id=2278978333088
2021-03-23 16:26:14,227 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059a626fe754e3c3c10e1b1 
2021-03-23 16:26:30,651 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 214 -> 214
2021-03-23 16:27:35,652 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 214 -> 214
2021-03-23 16:27:49,247 - ServiceFinder - INFO : [EtcdSupport.py:382]: recv wath expire, info--> BattleAllocatorCenter: ('192.168.82.177', 8888) - [217]
2021-03-23 16:28:51,251 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 217 -> 217
2021-03-23 16:30:01,252 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 217 -> 218
2021-03-23 16:31:02,257 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 218 -> 219
2021-03-23 16:32:03,259 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 219 -> 221
2021-03-23 16:33:05,261 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 221 -> 221
2021-03-23 16:34:11,263 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 221 -> 223
2021-03-23 16:35:20,265 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 223 -> 225
2021-03-23 16:36:30,253 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 225 -> 225
2021-03-23 16:37:31,256 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 225 -> 227
2021-03-23 16:38:32,257 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 227 -> 228
2021-03-23 16:39:35,259 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 228 -> 229
2021-03-23 16:40:40,263 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 229 -> 231
2021-03-23 16:41:47,267 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 231 -> 231
2021-03-23 16:42:47,284 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 231 -> 233
2021-03-23 16:43:49,288 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 233 -> 235
2021-03-23 16:44:56,290 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 235 -> 235
2021-03-23 16:46:00,292 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 235 -> 237
2021-03-23 16:47:07,295 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 237 -> 237
2021-03-23 16:48:14,641 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-23 16:48:14,643 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-23 16:48:14,648 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T08:51:14.6459976Z","ttl":180,"modifiedIndex":243,"createdIndex":243},"prevNode":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T08:50:49.8250784Z","ttl":156,"modifiedIndex":240,"createdIndex":240}}

2021-03-23 16:48:18,652 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-23 16:48:18,653 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 6059ab52fe754e3f68321118 mem_id=2178334224192
2021-03-23 16:48:18,655 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059ab52fe754e3f68321118 
2021-03-23 16:48:18,656 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-23 16:48:18,657 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-23 16:48:19,644 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-23 16:48:19,647 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-23 16:48:19,648 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-23 16:48:19,649 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-23 16:48:19,650 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 244
2021-03-23 16:49:29,656 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 244 -> 244
2021-03-23 16:50:29,661 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 244 -> 244
2021-03-23 16:53:11,605 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-23 16:53:11,606 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-23 16:53:11,623 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T08:56:11.6205258Z","ttl":180,"modifiedIndex":252,"createdIndex":252}}

2021-03-23 16:53:15,613 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-23 16:53:15,614 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 6059ac7bfe754e454cc3bd11 mem_id=1459562972928
2021-03-23 16:53:15,616 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059ac7bfe754e454cc3bd11 
2021-03-23 16:53:15,617 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-23 16:53:15,618 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-23 16:53:16,606 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-23 16:53:16,607 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-23 16:53:16,609 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-23 16:53:16,610 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 252
2021-03-23 16:54:26,618 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 252 -> 252
2021-03-23 16:55:20,751 - ServiceFinder - INFO : [EtcdSupport.py:371]: recv watch set service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888) - [254]
2021-03-23 16:55:20,752 - ServiceFinder - INFO : [EtcdSupport.py:258]: duplicate service info  -> BattleAllocatorCenter:('192.168.82.177', 8888)
2021-03-23 16:56:26,755 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 254 -> 254
2021-03-23 16:57:32,757 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 254 -> 254
2021-03-23 16:58:42,762 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 254 -> 256
2021-03-23 16:59:48,764 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 256 -> 257
2021-03-23 17:00:53,756 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 257 -> 258
2021-03-23 17:01:53,760 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 258 -> 260
2021-03-23 17:03:00,762 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 260 -> 260
2021-03-23 17:04:03,765 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 260 -> 262
2021-03-23 17:05:05,753 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 262 -> 263
2021-03-23 17:06:08,763 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 263 -> 264
2021-03-23 17:07:17,764 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 264 -> 266
2021-03-23 17:08:20,753 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 266 -> 267
2021-03-23 17:09:24,756 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 267 -> 268
2021-03-23 17:10:28,760 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 268 -> 270
2021-03-23 17:11:33,766 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 270 -> 270
2021-03-23 17:12:42,768 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 270 -> 272
2021-03-23 17:13:44,771 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 272 -> 273
2021-03-23 17:14:48,774 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 273 -> 274
2021-03-23 17:15:48,776 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 274 -> 276
2021-03-23 17:16:49,781 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 276 -> 276
2021-03-23 17:17:20,265 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,269 - ServiceFinder - INFO : [EtcdSupport.py:382]: recv wath expire, info--> BattleAllocatorStub: ('192.168.82.177', 8889) - [277]
2021-03-23 17:17:20,272 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,276 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,280 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,284 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,288 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,291 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,294 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,298 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:17:20,302 - ServiceRegister - ERROR : [EtcdSupport.py:186]: refresh service: BattleAllocatorStub error, {"errorCode":100,"message":"Key not found","cause":"/services/BattleAllocatorStub/192.168.82.177|8889","index":278}

2021-03-23 17:18:22,280 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 277 -> 278
2021-03-23 17:19:22,270 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 278 -> 278
2021-03-23 17:20:24,273 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 278 -> 279
2021-03-23 17:21:30,276 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 279 -> 279
2021-03-23 17:22:30,280 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 279 -> 280
2021-03-23 17:48:26,973 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-23 17:48:26,974 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-23 17:48:26,995 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|8889","value":"","expiration":"2021-03-23T09:51:26.989989Z","ttl":180,"modifiedIndex":288,"createdIndex":288}}

2021-03-23 17:48:30,987 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-23 17:48:30,990 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 6059b96efe754e46d4b2a253 mem_id=1975332033632
2021-03-23 17:48:30,993 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059b96efe754e46d4b2a253 
2021-03-23 17:48:30,996 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-23 17:48:30,998 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-23 17:48:31,987 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-23 17:48:31,993 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-23 17:48:31,995 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-23 17:48:31,998 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-23 17:48:32,000 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 289
2021-03-23 17:48:43,673 - ServerEntity.Puppet - INFO : [ServerEntity.py:21]: __init__ create entity Puppet with id 6059b97bfe754e46d4b2a254 mem_id=1975332968240
2021-03-23 17:48:43,677 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059b97bfe754e46d4b2a254 
2021-03-23 17:49:45,682 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 289 -> 289
2021-03-23 17:50:52,680 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 289 -> 290
2021-03-23 17:50:53,825 - ServerEntity.Puppet - INFO : [ServerEntity.py:21]: __init__ create entity Puppet with id 6059b9fdfe754e46d4b2a255 mem_id=1975332968672
2021-03-23 17:50:53,828 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  6059b9fdfe754e46d4b2a255 
