2021-03-24 09:03:13,237 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-24 09:03:13,240 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-24 09:03:13,241 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-24 09:03:13,242 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-24 09:03:13,243 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 13
