2021-03-16 10:13:21,872 - ServiceNode - INFO : [EtcdSupport.py:470]: we have create ServiceRegister, wait 5 seconds
2021-03-16 10:13:21,874 - ServiceNode - INFO : [EtcdSupport.py:473]: we have create ServiceFinder
2021-03-16 10:13:21,888 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorCenter success, {"action":"set","node":{"key":"/services/BattleAllocatorCenter/127.0.0.1|8888","value":"","expiration":"2021-03-16T02:16:21.8868103Z","ttl":180,"modifiedIndex":20,"createdIndex":20}}

2021-03-16 10:13:25,876 - ServerEntity.BattleAllocatorCenter - INFO : [ServerEntity.py:16]: __init__ create entity BattleAllocatorCenter with id 60501445fe754e207cf8377f mem_id=2157614358048
2021-03-16 10:13:25,877 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60501445fe754e207cf8377f 
2021-03-16 10:13:25,878 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 10:13:25,879 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 10:13:26,867 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 10:13:26,868 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 20
2021-03-16 10:14:36,874 - ServiceFinder - INFO : [EtcdSupport.py:416]: etcd watch timeout, rest watch index 20 -> 20
2021-03-16 10:14:53,269 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 10:14:53,271 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 10:14:53,275 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorCenter success, {"action":"set","node":{"key":"/services/BattleAllocatorCenter/127.0.0.1|8888","value":"","expiration":"2021-03-16T02:17:53.2745599Z","ttl":180,"modifiedIndex":21,"createdIndex":21},"prevNode":{"key":"/services/BattleAllocatorCenter/127.0.0.1|8888","value":"","expiration":"2021-03-16T02:16:21.8868103Z","ttl":89,"modifiedIndex":20,"createdIndex":20}}

2021-03-16 10:14:57,279 - ServerEntity.BattleAllocatorCenter - INFO : [ServerEntity.py:16]: __init__ create entity BattleAllocatorCenter with id 605014a1fe754e290814dab9 mem_id=3158487752512
2021-03-16 10:14:57,281 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  605014a1fe754e290814dab9 
2021-03-16 10:14:57,282 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 10:14:57,283 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 10:14:58,286 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 10:14:58,287 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 21
2021-03-16 10:16:05,290 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 21 -> 21
2021-03-16 10:18:06,276 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 10:18:06,277 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 10:18:06,292 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorCenter success, {"action":"set","node":{"key":"/services/BattleAllocatorCenter/127.0.0.1|8888","value":"","expiration":"2021-03-16T02:21:06.2902154Z","ttl":180,"modifiedIndex":23,"createdIndex":23},"prevNode":{"key":"/services/BattleAllocatorCenter/127.0.0.1|8888","value":"","expiration":"2021-03-16T02:19:38.2932763Z","ttl":93,"modifiedIndex":22,"createdIndex":22}}

2021-03-16 10:18:10,280 - ServerEntity.BattleAllocatorCenter - INFO : [ServerEntity.py:16]: __init__ create entity BattleAllocatorCenter with id 60501562fe754e2b9cd5d69e mem_id=1826828227488
2021-03-16 10:18:10,282 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60501562fe754e2b9cd5d69e 
2021-03-16 10:18:10,283 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 10:18:10,284 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 10:18:11,271 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 10:18:11,272 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 23
2021-03-16 10:19:15,275 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 23 -> 23
2021-03-16 10:20:24,281 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 23 -> 23
2021-03-16 10:21:24,285 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 23 -> 24
2021-03-16 10:22:28,291 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 24 -> 24
2021-03-16 10:23:30,294 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 24 -> 25
2021-03-16 10:24:36,298 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 25 -> 26
2021-03-16 10:25:41,299 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 26 -> 26
2021-03-16 10:26:42,302 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 26 -> 27
2021-03-16 10:27:43,304 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 27 -> 27
2021-03-16 10:28:48,312 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 27 -> 28
2021-03-16 10:29:49,316 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 28 -> 29
2021-03-16 10:30:49,317 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 29 -> 29
2021-03-16 10:31:52,320 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 29 -> 30
2021-03-16 10:32:59,322 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 30 -> 30
2021-03-16 10:33:54,188 - ServiceFinder - INFO : [EtcdSupport.py:369]: recv watch set service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888) - [33]
2021-03-16 10:33:54,189 - ServiceFinder - INFO : [EtcdSupport.py:257]: duplicate service info  -> BattleAllocatorCenter:('127.0.0.1', 8888)
2021-03-16 10:34:16,963 - ServiceFinder - ERROR : on_traceback, type:<class 'asyncio.exceptions.CancelledError'>, value:, traceback:<class 'asyncio.exceptions.CancelledError'>

  File "D:\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 412, in _watch_process
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001A957697BE0>, }
  File "C:\Program Files\Python38\lib\asyncio\tasks.py", line 484, in wait_for
    locals={'fut': <Task cancelled name='Task-24' coro=<ServiceFinder._watch_process_impl() done, defined at D:\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py:347>>, 'timeout': 65, 'loop': <ProactorEventLoop running=True closed=False debug=False>, 'waiter': <Future cancelled>, 'timeout_handle': <TimerHandle cancelled when=6031.0>, 'cb': functools.partial(<function _release_waiter at 0x000001A956C1B550>, <Future cancelled>)}
2021-03-16 10:38:30,808 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 10:38:30,808 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 10:38:30,818 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T02:41:30.8142182Z","ttl":180,"modifiedIndex":36,"createdIndex":36}}

2021-03-16 10:38:34,808 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 10:38:34,811 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:16]: __init__ create entity BattleAllocatorStub with id 60501a2afe754e14e076f470 mem_id=2050433199984
2021-03-16 10:38:34,814 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60501a2afe754e14e076f470 
2021-03-16 10:38:34,817 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 10:38:34,819 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:05:33,316 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:05:33,316 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:05:33,326 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:08:33.3224899Z","ttl":180,"modifiedIndex":40,"createdIndex":40}}

2021-03-16 16:05:37,317 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:05:37,320 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:19]: __init__ create entity BattleAllocatorStub with id 605066d1fe754e47a8905197 mem_id=1522115975440
2021-03-16 16:05:37,324 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  605066d1fe754e47a8905197 
2021-03-16 16:05:37,326 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:05:37,328 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:05:53,607 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:05:53,608 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:05:53,618 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:08:53.6148472Z","ttl":180,"modifiedIndex":41,"createdIndex":41},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:08:33.3224899Z","ttl":160,"modifiedIndex":40,"createdIndex":40}}

2021-03-16 16:05:57,630 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:05:57,637 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:19]: __init__ create entity BattleAllocatorStub with id 605066e5fe754e1ebc0042ce mem_id=3005017333616
2021-03-16 16:05:57,652 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  605066e5fe754e1ebc0042ce 
2021-03-16 16:05:57,655 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:05:57,664 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:06:22,599 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:06:22,601 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:06:26,757 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 41
2021-03-16 16:09:05,851 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 41 -> 41
2021-03-16 16:10:43,908 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:10:43,909 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:10:43,913 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:13:43.9122083Z","ttl":180,"modifiedIndex":46,"createdIndex":46},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:11:31.9044468Z","ttl":48,"modifiedIndex":43,"createdIndex":43}}

2021-03-16 16:10:47,917 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:10:47,919 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:19]: __init__ create entity BattleAllocatorStub with id 60506807fe754e3f1854708a mem_id=2276629709344
2021-03-16 16:10:47,921 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506807fe754e3f1854708a 
2021-03-16 16:10:47,922 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:10:47,923 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:10:48,924 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:52]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:10:48,927 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:10:48,928 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:10:48,929 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 46
2021-03-16 16:11:55,933 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 46 -> 46
2021-03-16 16:12:21,821 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:12:21,822 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:12:21,843 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:15:21.8394695Z","ttl":180,"modifiedIndex":48,"createdIndex":48},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:13:43.9122083Z","ttl":83,"modifiedIndex":46,"createdIndex":46}}

2021-03-16 16:12:25,833 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:12:25,836 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:19]: __init__ create entity BattleAllocatorStub with id 60506869fe754e328caa0839 mem_id=1924103971840
2021-03-16 16:12:25,839 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506869fe754e328caa0839 
2021-03-16 16:12:25,842 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:12:25,844 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:12:44,388 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:53]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:12:44,391 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:12:44,393 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:12:44,395 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 48
2021-03-16 16:13:46,405 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 48 -> 48
2021-03-16 16:14:47,401 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 48 -> 48
2021-03-16 16:15:11,780 - ServiceFinder - INFO : [EtcdSupport.py:380]: recv wath expire, info--> BattleAllocatorCenter: ('127.0.0.1', 8888) - [50]
2021-03-16 16:16:18,777 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 50 -> 50
2021-03-16 16:16:56,512 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:16:56,512 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:16:56,523 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:19:56.519265Z","ttl":180,"modifiedIndex":53,"createdIndex":53},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:18:44.8340676Z","ttl":109,"modifiedIndex":51,"createdIndex":51}}

2021-03-16 16:17:00,513 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:17:00,517 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:19]: __init__ create entity BattleAllocatorStub with id 6050697cfe754e3fe856164d mem_id=2880927288576
2021-03-16 16:17:00,520 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  6050697cfe754e3fe856164d 
2021-03-16 16:17:00,522 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:17:00,525 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:17:01,514 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:53]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:17:01,520 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:17:01,522 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:17:01,524 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 53
2021-03-16 16:18:03,533 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 53 -> 53
2021-03-16 16:19:11,526 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 53 -> 53
2021-03-16 16:19:53,280 - ServiceFinder - INFO : [EtcdSupport.py:380]: recv wath expire, info--> BattleAllocatorCenter: ('127.0.0.1', 8888) - [55]
2021-03-16 16:21:03,285 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 55 -> 55
2021-03-16 16:22:04,292 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 55 -> 56
2021-03-16 16:23:09,287 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 56 -> 56
2021-03-16 16:24:09,295 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 56 -> 57
2021-03-16 16:25:13,286 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 57 -> 58
2021-03-16 16:26:20,293 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 58 -> 58
2021-03-16 16:27:20,299 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 58 -> 59
2021-03-16 16:28:25,308 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 59 -> 59
2021-03-16 16:29:25,315 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 59 -> 60
2021-03-16 16:30:32,322 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 60 -> 61
2021-03-16 16:31:38,330 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 61 -> 61
2021-03-16 16:32:45,324 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 61 -> 62
2021-03-16 16:33:38,399 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:33:38,400 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:33:38,411 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:36:38.4073752Z","ttl":180,"modifiedIndex":65,"createdIndex":65},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:35:38.6484402Z","ttl":121,"modifiedIndex":63,"createdIndex":63}}

2021-03-16 16:33:42,400 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:33:42,404 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 60506d66fe754e4624eebe45 mem_id=1858009755856
2021-03-16 16:33:42,407 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506d66fe754e4624eebe45 
2021-03-16 16:33:42,409 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:33:42,411 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:33:43,399 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:53]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:33:43,405 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:33:43,408 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:33:43,410 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 65
2021-03-16 16:34:31,700 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:34:31,700 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:34:31,711 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:37:31.7067131Z","ttl":180,"modifiedIndex":66,"createdIndex":66},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:36:38.4073752Z","ttl":127,"modifiedIndex":65,"createdIndex":65}}

2021-03-16 16:34:35,701 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:34:35,705 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 60506d9bfe754e4148de8272 mem_id=1728656215728
2021-03-16 16:34:35,709 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506d9bfe754e4148de8272 
2021-03-16 16:34:35,711 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:34:35,713 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:34:36,705 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:34:36,707 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:34:36,713 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 66
2021-03-16 16:35:44,943 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:35:44,943 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:35:44,964 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:38:44.960373Z","ttl":180,"modifiedIndex":67,"createdIndex":67},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:37:31.7067131Z","ttl":107,"modifiedIndex":66,"createdIndex":66}}

2021-03-16 16:35:52,541 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:35:52,541 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:35:52,551 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:38:52.547958Z","ttl":180,"modifiedIndex":69,"createdIndex":69},"prevNode":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:38:44.960373Z","ttl":173,"modifiedIndex":67,"createdIndex":67}}

2021-03-16 16:35:56,542 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:35:56,545 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 60506decfe754e2dacc60f7a mem_id=2119401135840
2021-03-16 16:35:56,548 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506decfe754e2dacc60f7a 
2021-03-16 16:35:56,550 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:35:56,553 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:35:57,540 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:53]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:35:57,546 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:35:57,549 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:35:57,551 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 69
2021-03-16 16:39:22,399 - ServiceNode - INFO : [EtcdSupport.py:474]: we have create ServiceRegister, wait 5 seconds
2021-03-16 16:39:22,400 - ServiceNode - INFO : [EtcdSupport.py:477]: we have create ServiceFinder
2021-03-16 16:39:22,421 - ServiceRegister - INFO : [EtcdSupport.py:147]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/127.0.0.1|8889","value":"","expiration":"2021-03-16T08:42:22.4177295Z","ttl":180,"modifiedIndex":73,"createdIndex":73}}

2021-03-16 16:39:26,412 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-16 16:39:26,415 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 60506ebefe754e3d381267d7 mem_id=2179441987104
2021-03-16 16:39:26,418 - server.EntityManager - INFO : [EntityManager.py:127]: addentity  entity id  60506ebefe754e3d381267d7 
2021-03-16 16:39:26,421 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-16 16:39:26,423 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-16 16:39:27,414 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:53]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-16 16:39:27,416 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorCenter: ('127.0.0.1', 8888)
2021-03-16 16:39:27,419 - ServiceFinder - INFO : [EtcdSupport.py:281]: add service node info--> BattleAllocatorStub: ('127.0.0.1', 8889)
2021-03-16 16:39:27,421 - ServiceFinder - INFO : [EtcdSupport.py:235]: init service info from etcd success, will going to watch, at etcd index -> 73
2021-03-16 16:41:01,924 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 73 -> 73
2021-03-16 16:42:02,931 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 73 -> 73
2021-03-16 16:43:10,941 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 73 -> 75
2021-03-16 16:44:15,948 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 75 -> 77
2021-03-16 16:45:22,955 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 77 -> 77
2021-03-16 16:46:26,950 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 77 -> 79
2021-03-16 16:47:31,957 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 79 -> 81
2021-03-16 16:48:36,965 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 81 -> 81
2021-03-16 16:49:37,710 - ClientEntity.Puppet - INFO : [ClientEntity.py:16]: __init__ create entity Puppet with id 60507121fe754e1530eb9e3d mem_id=1520790095856
2021-03-16 16:49:43,972 - ServiceFinder - INFO : [EtcdSupport.py:420]: etcd watch timeout, rest watch index 81 -> 83
